name: build
on:
  create:
    tags:
      - v*.*.*
permissions:
  contents: write
jobs:
  create-release:
    name: Create release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Chaekout
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run build
        run: |
          npm install
          npm run dump minenohara_dic_v2 -- -r requirements.txt
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          skip_build: true
          args: deb rpm
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
  # create-release-mac:
  #   name: Create Mac release
  #   runs-on: macos-latest
  #   steps:
  #     - name: Chaekout
  #       uses: actions/checkout@v3
  #     - name: Use Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         build_script_name: dump minenohara_dic_v2 -- -r requirements.txt
  #         args: -m
  #         release: ${{ startsWith(github.ref, 'refs/tags/v') }}