name: build
on:
  create:
    tags:
      - v*.*.*
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Chaekout
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm i
          npm run dump minenohara_dic_v2 -- -r requirements.txt
          npm run dist -- -wl deb rpm
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.pull_request.body }}
          tag_name: ${{ github.event.pull_request.title }}
          generate_release_notes: true
          files: |
            dist/minenohara_dic_v2 Setup *.exe
            dist/minenohara_dic_v2_*.deb
            dist/minenohara_dic_v2_*.rpm
            # dist/minenohara_dic_v2-*.dmg
  create-release-mac:
    name: Create release
    runs-on: macos-latest
    steps:
      - name: Chaekout
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm i
          npm run dump minenohara_dic_v2 -- -r requirements.txt
          npm run dist -- -m
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.pull_request.body }}
          tag_name: ${{ github.event.pull_request.title }}
          generate_release_notes: true
          files: |
            dist/minenohara_dic_v2-*.dmg