name: build
on:
  create:
    tags:
      - v*.*.*
permissions:
  contents: write
jobs:
  create-release:
    name: Create release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Chaekout
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run build
        run: |
          npm install
          npm run dump minenohara_dic_v2 -- -r requirements.txt
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          skip_build: true
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
